format_version: v1.0
type: UniqueComponent
attributes: {id: usb_device}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_CONFIG_DESCRPTR_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '67'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_ENDPOINTS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '2'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_FUNCTIONS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_INTERFACES_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '2'}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_MANUFACTURER_STRING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Ferris IOT Security}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_MSD_DISK_IMAGE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: 'false'}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '0x0000'}
      - type: User
        attributes: {value: '0x0001'}
  - type: Combo
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_SELECTION_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Enter Product ID}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_STRING_DESCRIPTOR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: Enter Product String Here}
      - type: User
        attributes: {value: Atmospheric Sensor Module}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_VENDOR_ID_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0x0005'}
- type: ElementPosition
  attributes: {x: '233', y: '230', id: usb_device}
